"""empty message

Revision ID: 113026d3c98f
Revises: 6ea47fd76d53
Create Date: 2018-09-24 15:12:54.272944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '113026d3c98f'
down_revision = '6ea47fd76d53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package', sa.Column('is_control_services_restart', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('package', 'is_control_services_restart')
    # ### end Alembic commands ###
