"""empty message

Revision ID: 6ea47fd76d53
Revises: 
Create Date: 2017-12-06 19:05:09.979776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ea47fd76d53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('update_package', sa.Column('version_from', sa.String(length=255), nullable=True))
    op.add_column('update_package', sa.Column('version_to', sa.String(length=255), nullable=True))
    op.drop_column('update_package', 'version')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('update_package', sa.Column('version', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('update_package', 'version_to')
    op.drop_column('update_package', 'version_from')
    # ### end Alembic commands ###
