"""empty message

Revision ID: f9833bf4cc1f
Revises: 113026d3c98f
Create Date: 2018-09-24 22:41:33.050688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9833bf4cc1f'
down_revision = '113026d3c98f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package_service', sa.Column('position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('package_service', 'position')
    # ### end Alembic commands ###
