stages:
  - test
  - package
  - deploy

test:debian:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y curl gnupg apt-transport-https python3-dev python3-pip
    - pip3 install -r requirements.txt
    - python3 setup.py test
  tags:
    - debian



package:debian:
  stage: package
  script:
    - apt-get update -qy
    - apt-get install -y curl gnupg apt-transport-https wget
    - wget -O- https://repository.salamek.cz/deb/salamek.gpg | tee /usr/share/keyrings/salamek-archive-keyring.gpg
    - echo "deb     [signed-by=/usr/share/keyrings/salamek-archive-keyring.gpg] https://repository.salamek.cz/deb/pub all main" | tee /etc/apt/sources.list.d/salamek.cz.list
    - apt-get update -qy
    - apt-get install -y sudo python3-flask-celery-tools python3-dev dh-python python3-pip python3-stdeb python3-celery python3-markupsafe python3-eventlet python3-psycopg2 python3-dateutil python3-lxml python3-docopt python3-netifaces python3-yaml python3-raven python3-flask-migrate python3-flask-babel python3-socketio python3-flask-socketio python3-kombu rabbitmq-server python3-python-flask-jwt-extended python3-flask-cors
    - rm -rf "./deb_dist"
    - python3 setup.py --command-packages=stdeb.command bdist_deb
  tags:
    - debian

  artifacts:
    paths:
      - deb_dist/*.deb
    expire_in: 1d



deploy:all:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh www-data@repository 'rm -rf /var/www/repository.salamek.cz/cache/deb/pub/all/tux-control*.deb'
    - scp deb_dist/*.deb www-data@repository:/var/www/repository.salamek.cz/cache/deb/pub/all
    - ssh www-data@repository '/var/www/repository.salamek.cz/deb-pub-update.sh'
  dependencies:
    - package:debian
  tags:
    - docker
  only:
    - tags